// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// build_bitset_unpaired
List build_bitset_unpaired(const List& hits_by_peptide, const int N);
RcppExport SEXP _phiper_build_bitset_unpaired(SEXP hits_by_peptideSEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type hits_by_peptide(hits_by_peptideSEXP);
    Rcpp::traits::input_parameter< const int >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(build_bitset_unpaired(hits_by_peptide, N));
    return rcpp_result_gen;
END_RCPP
}
// cpp_shift_contrast
Rcpp::List cpp_shift_contrast(const Rcpp::RawVector& bitset_raw, const int n_words, const Rcpp::IntegerVector& pep_cols, const Rcpp::IntegerVector& g1_rows, const Rcpp::IntegerVector& g2_rows, const Rcpp::List& hits_g1_paired, const Rcpp::List& hits_g2_paired, const int P, const int B, const int seed, const std::string& weight_mode, const std::string& stat_mode, const std::string& aggregate_stat, const Rcpp::NumericVector& strat_bins, const double winsor_z, const std::string& design);
RcppExport SEXP _phiper_cpp_shift_contrast(SEXP bitset_rawSEXP, SEXP n_wordsSEXP, SEXP pep_colsSEXP, SEXP g1_rowsSEXP, SEXP g2_rowsSEXP, SEXP hits_g1_pairedSEXP, SEXP hits_g2_pairedSEXP, SEXP PSEXP, SEXP BSEXP, SEXP seedSEXP, SEXP weight_modeSEXP, SEXP stat_modeSEXP, SEXP aggregate_statSEXP, SEXP strat_binsSEXP, SEXP winsor_zSEXP, SEXP designSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::RawVector& >::type bitset_raw(bitset_rawSEXP);
    Rcpp::traits::input_parameter< const int >::type n_words(n_wordsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type pep_cols(pep_colsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type g1_rows(g1_rowsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type g2_rows(g2_rowsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type hits_g1_paired(hits_g1_pairedSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type hits_g2_paired(hits_g2_pairedSEXP);
    Rcpp::traits::input_parameter< const int >::type P(PSEXP);
    Rcpp::traits::input_parameter< const int >::type B(BSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type weight_mode(weight_modeSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type stat_mode(stat_modeSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type aggregate_stat(aggregate_statSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type strat_bins(strat_binsSEXP);
    Rcpp::traits::input_parameter< const double >::type winsor_z(winsor_zSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type design(designSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_shift_contrast(bitset_raw, n_words, pep_cols, g1_rows, g2_rows, hits_g1_paired, hits_g2_paired, P, B, seed, weight_mode, stat_mode, aggregate_stat, strat_bins, winsor_z, design));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_phiper_build_bitset_unpaired", (DL_FUNC) &_phiper_build_bitset_unpaired, 2},
    {"_phiper_cpp_shift_contrast", (DL_FUNC) &_phiper_cpp_shift_contrast, 15},
    {NULL, NULL, 0}
};

RcppExport void R_init_phiper(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
