name: pkgcheck

# This will cancel running jobs once a new run is triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

on:
  push:
    paths:
      - "R/**"
      - "tests/**"
      - "DESCRIPTION"
      - "NAMESPACE"
  pull_request:
    paths:
      - "R/**"
      - "tests/**"
      - "DESCRIPTION"
      - "NAMESPACE"
  workflow_dispatch:

jobs:
  pkgcheck:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: ropensci-review-tools/pkgcheck-action@main
